/* eslint-disable */
export default {
  "key": "trips-page",
  "content": {
    "nodeType": "translation",
    "translation": {
      "en": {
        "metadata": {
          "title": "Please Sign In to view your trips."
        },
        "wel": "Welcome back,",
        "dashboard": "Dashboard",
        "dashboardSubtitle": "Manage and explore your travel adventures",
        "newTrip": "New Trip",
        "yourRecentTrips": "Your Recent Trips",
        "totalTrips": "Total Trips",
        "totalTrip": "Total Trip",
        "memories": "Memories",
        "noTripsYet": "No trips yet",
        "emptyStateMessage": "Start planning your adventure by creating your first trip. The world is waiting for you! 🌍",
        "createFirstTrip": "Create Your First Trip",
        "upcoming": "Upcoming",
        "previus": "Previous Trips",
        "pastAdventures": "Past Adventures",
        "daysUntilToday": "Today!",
        "dayAway": "day away",
        "daysAway": "days away",
        "deleteTrip": "Delete Trip",
        "confirmDeleteTitle": "Delete Trip",
        "confirmDeleteDescription": "Are you sure you want to delete this trip? This action cannot be undone and will delete all locations and activities.",
        "confirmDelete": "Delete",
        "cancel": "Cancel",
        "upcomingTrips": "Upcoming Trips",
        "pastTrips": "Past Trips",
        "trip": "Trip",
        "trips": "Trips",
        "viewTrip": "View Trip",
        "editTrip": "Edit Trip",
        "tripDetails": "Trip Details",
        "startDate": "Start Date",
        "endDate": "End Date",
        "description": "Description",
        "noDescription": "No description provided",
        "loading": "Loading...",
        "errorLoadingTrips": "Error loading trips",
        "tryAgain": "Try Again",
        "createTrip": "Create Trip",
        "searchTrips": "Search trips...",
        "filterBy": "Filter by",
        "sortBy": "Sort by",
        "allTrips": "All Trips"
      },
      "fr": {
        "metadata": {
          "title": "Veuillez vous connecter pour voir vos voyages."
        },
        "wel": "Bon retour,",
        "dashboard": "Tableau de bord",
        "dashboardSubtitle": "Gérez et explorez vos aventures de voyage",
        "newTrip": "Nouveau voyage",
        "yourRecentTrips": "Vos voyages récents",
        "totalTrips": "Total voyages",
        "totalTrip": "Total voyage",
        "memories": "Souvenirs",
        "noTripsYet": "Aucun voyage pour l'instant",
        "emptyStateMessage": "Commencez à planifier votre aventure en créant votre premier voyage. Le monde vous attend ! 🌍",
        "createFirstTrip": "Créer votre premier voyage",
        "upcoming": "À venir",
        "previus": "Voyages précédents",
        "pastAdventures": "Aventures passées",
        "daysUntilToday": "Aujourd'hui !",
        "dayAway": "jour",
        "daysAway": "jours",
        "deleteTrip": "Supprimer le voyage",
        "confirmDeleteTitle": "Supprimer le voyage",
        "confirmDeleteDescription": "Êtes-vous sûr de vouloir supprimer ce voyage ? Cette action est irréversible et supprimera tous les lieux et activités.",
        "confirmDelete": "Supprimer",
        "cancel": "Annuler",
        "upcomingTrips": "Voyages à venir",
        "pastTrips": "Voyages passés",
        "trip": "Voyage",
        "trips": "Voyages",
        "viewTrip": "Voir le voyage",
        "editTrip": "Modifier le voyage",
        "tripDetails": "Détails du voyage",
        "startDate": "Date de début",
        "endDate": "Date de fin",
        "description": "Description",
        "noDescription": "Aucune description fournie",
        "loading": "Chargement...",
        "errorLoadingTrips": "Erreur lors du chargement des voyages",
        "tryAgain": "Réessayer",
        "createTrip": "Créer un voyage",
        "searchTrips": "Rechercher des voyages...",
        "filterBy": "Filtrer par",
        "sortBy": "Trier par",
        "allTrips": "Tous les voyages"
      },
      "es": {
        "metadata": {
          "title": "Por favor inicia sesión para ver tus viajes."
        },
        "wel": "Bienvenido de nuevo,",
        "dashboard": "Panel de control",
        "dashboardSubtitle": "Gestiona y explora tus aventuras de viaje",
        "newTrip": "Nuevo viaje",
        "yourRecentTrips": "Tus viajes recientes",
        "totalTrips": "Total viajes",
        "totalTrip": "Total viaje",
        "memories": "Recuerdos",
        "noTripsYet": "Aún no hay viajes",
        "emptyStateMessage": "Comienza a planificar tu aventura creando tu primer viaje. ¡El mundo te espera! 🌍",
        "createFirstTrip": "Crear tu primer viaje",
        "upcoming": "Próximo",
        "previus": "Viajes anteriores",
        "pastAdventures": "Aventuras pasadas",
        "daysUntilToday": "¡Hoy!",
        "dayAway": "día",
        "daysAway": "días",
        "deleteTrip": "Eliminar viaje",
        "confirmDeleteTitle": "Eliminar viaje",
        "confirmDeleteDescription": "¿Estás seguro de que quieres eliminar este viaje? Esta acción no se puede deshacer y eliminará todas las ubicaciones y actividades.",
        "confirmDelete": "Eliminar",
        "cancel": "Cancelar",
        "upcomingTrips": "Próximos viajes",
        "pastTrips": "Viajes pasados",
        "trip": "Viaje",
        "trips": "Viajes",
        "viewTrip": "Ver viaje",
        "editTrip": "Editar viaje",
        "tripDetails": "Detalles del viaje",
        "startDate": "Fecha de inicio",
        "endDate": "Fecha de fin",
        "description": "Descripción",
        "noDescription": "No hay descripción proporcionada",
        "loading": "Cargando...",
        "errorLoadingTrips": "Error al cargar los viajes",
        "tryAgain": "Intentar de nuevo",
        "createTrip": "Crear viaje",
        "searchTrips": "Buscar viajes...",
        "filterBy": "Filtrar por",
        "sortBy": "Ordenar por",
        "allTrips": "Todos los viajes"
      }
    }
  },
  "localIds": [
    "trips-page::local::app/[locale]/trips/page.content.ts"
  ]
} as const;
